FROM docker.io/library/node:22-bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    zsh git ripgrep fd-find findutils grep sed gawk curl ca-certificates less procps bubblewrap socat \
    libnotify-bin \
  && rm -rf /var/lib/apt/lists/* \
  && ln -s /usr/bin/fdfind /usr/local/bin/fd || true

RUN npm install -g @anthropic-ai/claude-code opencode-ai bun
RUN apt install -y libnotify-bin

RUN useradd -m -s /usr/bin/zsh agent
USER agent
WORKDIR /workspace

ENV HOME=/home/agent \
    SHELL=/usr/bin/zsh \
    PATH=/home/agent/.npm-global/bin:/usr/local/bin:/usr/bin:/bin

ENTRYPOINT ["/usr/bin/zsh", "-lc"]
